name: Test SSH Connection

on:
  workflow_dispatch: # manually trigger from GitHub

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Hello from EC2!"
            whoami
            hostname
